const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("Deploying contracts with account:", deployer.address);
  console.log(
    "Account balance:",
    (await ethers.provider.getBalance(deployer.address)).toString()
  );

  // ─── Deploy MarketplaceNFT ─────────────────────────────────────────────────

  console.log("\n Deploying MarketplaceNFT...");
  const NFT = await ethers.getContractFactory("MarketplaceNFT");
  const nft = await NFT.deploy();
  await nft.waitForDeployment();
  const nftAddress = await nft.getAddress();
  console.log("MarketplaceNFT deployed to:", nftAddress);

  // ─── Deploy NFTMarketplace ─────────────────────────────────────────────────

  const PLATFORM_FEE = 250; // 2.5%
  const FEE_RECIPIENT = deployer.address; // change to multisig in production

  console.log("\n Deploying NFTMarketplace...");
  const Marketplace = await ethers.getContractFactory("NFTMarketplace");
  const marketplace = await Marketplace.deploy(PLATFORM_FEE, FEE_RECIPIENT);
  await marketplace.waitForDeployment();
  const marketplaceAddress = await marketplace.getAddress();
  console.log("NFTMarketplace deployed to:", marketplaceAddress);

  // ─── Save Addresses ────────────────────────────────────────────────────────

  const deploymentInfo = {
    network: hre.network.name,
    deployer: deployer.address,
    contracts: {
      MarketplaceNFT: nftAddress,
      NFTMarketplace: marketplaceAddress,
    },
    platformFeeBasisPoints: PLATFORM_FEE,
    feeRecipient: FEE_RECIPIENT,
    deployedAt: new Date().toISOString(),
  };

  const deploymentsDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir);
  }

  const filePath = path.join(deploymentsDir, `${hre.network.name}.json`);
  fs.writeFileSync(filePath, JSON.stringify(deploymentInfo, null, 2));
  console.log("\n Deployment info saved to:", filePath);

  // ─── Copy ABIs to frontend ─────────────────────────────────────────────────

  const frontendAbisDir = path.join(__dirname, "../frontend/src/abis");
  if (!fs.existsSync(frontendAbisDir)) {
    fs.mkdirSync(frontendAbisDir, { recursive: true });
  }

  const nftArtifact = require("../artifacts/contracts/MarketplaceNFT.sol/MarketplaceNFT.json");
  const marketplaceArtifact = require("../artifacts/contracts/NFTMarketplace.sol/NFTMarketplace.json");

  fs.writeFileSync(
    path.join(frontendAbisDir, "MarketplaceNFT.json"),
    JSON.stringify(nftArtifact.abi, null, 2)
  );

  fs.writeFileSync(
    path.join(frontendAbisDir, "NFTMarketplace.json"),
    JSON.stringify(marketplaceArtifact.abi, null, 2)
  );

  console.log(" ABIs copied to frontend/src/abis/");

  // ─── Save addresses to frontend constants ─────────────────────────────────

  const frontendUtilsDir = path.join(__dirname, "../frontend/src/utils");
  if (!fs.existsSync(frontendUtilsDir)) {
    fs.mkdirSync(frontendUtilsDir, { recursive: true });
  }

  const constantsContent = `// Auto-generated by deploy.js — do not edit manually
export const CONTRACT_ADDRESSES = {
  MarketplaceNFT: "${nftAddress}",
  NFTMarketplace: "${marketplaceAddress}",
};

export const NETWORK = {
  name: "${hre.network.name}",
  chainId: ${hre.network.config.chainId || 31337},
};
`;

  fs.writeFileSync(
    path.join(frontendUtilsDir, "constants.js"),
    constantsContent
  );
  console.log(" Contract addresses saved to frontend/src/utils/constants.js");

  console.log("\n Deploy complete.");
  console.log("─────────────────────────────────────────");
  console.log(" MarketplaceNFT :", nftAddress);
  console.log(" NFTMarketplace :", marketplaceAddress);
  console.log("─────────────────────────────────────────");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });