// Auto-generated by deploy.js — do not edit manually
export const CONTRACT_ADDRESSES = {
  MarketplaceNFT: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  NFTMarketplace: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
};

export const NETWORK = {
  name: "localhost",
  chainId: 31337,
};
